name: cloudsandsky
favicon: null
layout_spectrum: 0.8111024028621614
typography_spectrum: 0.2800677828490734
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.7591409666929394
  lightness: 0.8435807551722974
  saturation: 0.7095276128966361
  rhythmicContrast: 0.2655257717706263
purpose: []
