typography_spectrum: 0.3369175
color:
  brandColors:
    - '#f7f7f7'
    - '#191919'
    - '#9c9c9a'
    - '#2e667f'
    - '#dfc96a'
  brandStrength: 0
  lightness: 1
  saturation: 0
  rhythmicContrast: 0
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.50131
analytics:
  google: null
  facebook: null
  twitter: null
name: cloudsandsky
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: menu 2
    id: 9b2e68c4-2e04-4650-88ff-3c202e65dbfa
    type: content
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: cloudsandsky
purpose: []
