title: cloudsandsky
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.7095276128966361
  brandStrength: 0.1875
  rhythmicContrast: 0.2655257717706263
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  lightness: 0.8435807551722974
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: cloudsandsky
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.2800677828490734
layout_spectrum: 0.9820789
